<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CS2_Poor_Duels</RootNamespace>
    <AssemblyName>CS2_Poor_Duels</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.367" />
    <PackageReference Include="CS2MenuManager" Version="1.0.41" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <ProjectReference Include="../CS2_Poor_Duels_Api/CS2_Poor_Duels_Api.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
